version: "3"

services:
  nodeserver:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: nodeserver
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

    networks:
      - node-network

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    ports:
      - "80:80"
    depends_on:
      - nodeserver

networks:
  node-network:
    driver: bridge
